# source this file in ~/.zlogin, and enable auto login to see dmesg
# logs in tty1 after boot:
# source ~/src/homeepd/dev-133e6/paint

if [[ $(tty) == /dev/tty1 && -z "$SSH_CLIENT" ]]; then
    if [[ -z "$TMUX" ]]; then
        tmux new-session -d -s main
        tmux split-window -h -t main
        tmux send-keys -t main:0.0 'sudo dmesg -T --follow' C-m
        tmux send-keys -t main:0.1 'sleep 1; sudo python3 ~/src/homeepd/dev-133e6/paint/paint.py' C-m
        tmux attach -t main
    fi
fi
